name: certbot-dns-gandi CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract commit id
      id: extract_commit_id
      shell: bash
      run: echo "##[set-output name=commit_id;]$(git rev-parse HEAD | cut -c 1-8)"
    - name: Dockerhub login
      env:
        DH_USER: ${{ secrets.DH_USER }}
        DH_TOKEN: ${{ secrets.DH_TOKEN }}
      run: |
        echo "${DH_TOKEN}" | docker login --username ${DH_USER} --password-stdin
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: Build dockerfile (with push)
      run: |
        docker buildx build                             \
        --platform=linux/amd64,linux/arm/v7,linux/arm64 \
        --output "type=image,push=true"                 \
        --file ./Dockerfile .                           \
        --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/GITHUB_REPOSITORY:${{ steps.extract_commit_id.outputs.commit_id }}
        --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/GITHUB_REPOSITORY:latest
